version: '3.4'

services:
  shelflayout.server:
    image: ${DOCKER_REGISTRY-}shelflayoutserver
    container_name: shelf
    build:
      context: .
      dockerfile: ShelfLayout/Server/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ShelfLayout;User Id=sa;Password=saPassword1234;Encrypt=False"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "saPassword1234"
      MSSQL_PID: "Express"
      MSSQL_LCID: "1041"
      MSSQL_COLLATION: "Japanese_CI_AS"
    ports:
      - "1433:1433"
    volumes:
      - ./ShelfLayout/Shared/init-db.sql:/initdb/init-db.sql